### ISSUE TITLE
Website recommendation for types

### ISSUE THREAD

**Issue by bellwood** [itsjavi/supereffective-dataset#9]
Greetings, appreciate your interactive dataset!

Would it be possible, for types, to either give type options after typeing `type:` in the form field - or - add pre-made pill buttons under the search box for the possible types: [Fairy] [Bug] [Ghost] etc?

Thank you =)

**Comment by itsjavi** [comment]
hi, @bellwood  do you mean this search box in the supereffective.gg website?

![image](https://user-images.githubusercontent.com/122741/181799397-1538df60-3924-45fe-ab23-fb6540cfb337.png)

it would be nice to have autocomplete, but I'm prioritizing other needed features right now.
you can click on any type icon when checking a Pokemon though.

I am closing this, because it is not related to the dataset itself, but nice idea. Please use our discord to discuss about the website itself. Thx!
